# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
url:                 https://fpga.guide/
baseurl:             ''

# About/contact
author:
  name:              FPGA
  url:               https://twitter.com/fpgaguide
  email:             hello@fpga.guide

# Custom vars
version:             1.0.0

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag